FROM nginx:1.27-alpine
COPY deploy/nginx.conf /etc/nginx/conf.d/default.conf
COPY index.html /usr/share/nginx/html/
COPY styles /usr/share/nginx/html/styles
COPY js /usr/share/nginx/html/js
COPY docs /usr/share/nginx/html/docs
EXPOSE 80
