// Auto-generated by scripts/gen-sim-map.mjs — do not edit manually
export const SIM_MAP = {
  "lost-update": {
    "lab": "race",
    "figure": "timeline",
    "priority": "gold",
    "category": "concurrency",
    "track": "failures",
    "title": "Lost Update"
  },
  "toctou": {
    "lab": "race",
    "figure": "timeline",
    "priority": "failures",
    "category": "concurrency",
    "track": "failures",
    "title": "TOCTOU"
  },
  "aba": {
    "lab": "race",
    "figure": "none",
    "priority": "failures",
    "category": "concurrency",
    "track": "failures",
    "title": "ABA Problem"
  },
  "double-spend": {
    "lab": "race",
    "figure": "none",
    "priority": "failures",
    "category": "concurrency",
    "track": "failures",
    "title": "Double Spend"
  },
  "write-skew": {
    "lab": "race",
    "figure": "none",
    "priority": "failures",
    "category": "concurrency",
    "track": "failures",
    "title": "Write Skew"
  },
  "phantom-read": {
    "lab": "race",
    "figure": "none",
    "priority": "failures",
    "category": "concurrency",
    "track": "failures",
    "title": "Phantom Read"
  },
  "dirty-read": {
    "lab": "race",
    "figure": "none",
    "priority": "failures",
    "category": "concurrency",
    "track": "failures",
    "title": "Dirty Read"
  },
  "non-repeatable-read": {
    "lab": "race",
    "figure": "none",
    "priority": "failures",
    "category": "concurrency",
    "track": "failures",
    "title": "Non-repeatable Read"
  },
  "read-skew": {
    "lab": "race",
    "figure": "none",
    "priority": "failures",
    "category": "concurrency",
    "track": "failures",
    "title": "Read Skew"
  },
  "deadlock": {
    "lab": "race",
    "figure": "lockTimeline",
    "priority": "failures",
    "category": "locking",
    "track": "failures",
    "title": "Deadlock"
  },
  "lock-contention": {
    "lab": "race",
    "figure": "none",
    "priority": "failures",
    "category": "locking",
    "track": "failures",
    "title": "Lock Contention"
  },
  "lock-convoy": {
    "lab": "race",
    "figure": "none",
    "priority": "failures",
    "category": "locking",
    "track": "failures",
    "title": "Lock Convoy"
  },
  "priority-inversion": {
    "lab": "race",
    "figure": "none",
    "priority": "failures",
    "category": "locking",
    "track": "failures",
    "title": "Priority Inversion"
  },
  "livelock": {
    "lab": "race",
    "figure": "none",
    "priority": "failures",
    "category": "locking",
    "track": "failures",
    "title": "Livelock"
  },
  "starvation": {
    "lab": "race",
    "figure": "none",
    "priority": "failures",
    "category": "locking",
    "track": "failures",
    "title": "Starvation"
  },
  "retry-storm": {
    "lab": "metrics",
    "figure": "retryAmplification",
    "priority": "failures",
    "category": "retry",
    "track": "failures",
    "title": "Retry Storm"
  },
  "thundering-herd": {
    "lab": "metrics",
    "figure": "stampede",
    "priority": "failures",
    "category": "retry",
    "track": "failures",
    "title": "Thundering Herd"
  },
  "cache-stampede": {
    "lab": "metrics",
    "figure": "stampede",
    "priority": "failures",
    "category": "retry",
    "track": "failures",
    "title": "Cache Stampede"
  },
  "dogpile": {
    "lab": "metrics",
    "figure": "none",
    "priority": "failures",
    "category": "retry",
    "track": "failures",
    "title": "Dogpile Effect"
  },
  "retry-amplification": {
    "lab": "metrics",
    "figure": "retryAmplification",
    "priority": "failures",
    "category": "retry",
    "track": "failures",
    "title": "Retry Amplification"
  },
  "coordinated-omission": {
    "lab": "metrics",
    "figure": "none",
    "priority": "failures",
    "category": "retry",
    "track": "failures",
    "title": "Coordinated Omission"
  },
  "cache-invalidation": {
    "lab": "metrics",
    "figure": "none",
    "priority": "failures",
    "category": "cache",
    "track": "failures",
    "title": "Cache Invalidation"
  },
  "cache-consistency": {
    "lab": "metrics",
    "figure": "none",
    "priority": "failures",
    "category": "cache",
    "track": "failures",
    "title": "Cache Consistency"
  },
  "hot-key": {
    "lab": "metrics",
    "figure": "none",
    "priority": "failures",
    "category": "cache",
    "track": "failures",
    "title": "Hot Key"
  },
  "cache-pollution": {
    "lab": "metrics",
    "figure": "none",
    "priority": "failures",
    "category": "cache",
    "track": "failures",
    "title": "Cache Pollution"
  },
  "poison-message": {
    "lab": "queue",
    "figure": "none",
    "priority": "failures",
    "category": "messaging",
    "track": "failures",
    "title": "Poison Message"
  },
  "backpressure": {
    "lab": "queue",
    "figure": "none",
    "priority": "failures",
    "category": "messaging",
    "track": "failures",
    "title": "Backpressure"
  },
  "slow-consumer": {
    "lab": "queue",
    "figure": "none",
    "priority": "failures",
    "category": "messaging",
    "track": "failures",
    "title": "Slow Consumer"
  },
  "head-of-line-blocking": {
    "lab": "queue",
    "figure": "none",
    "priority": "failures",
    "category": "messaging",
    "track": "failures",
    "title": "Head-of-line Blocking"
  },
  "partial-failure": {
    "lab": "state",
    "figure": "none",
    "priority": "failures",
    "category": "failure",
    "track": "failures",
    "title": "Partial Failure"
  },
  "cascading-failure": {
    "lab": "state",
    "figure": "domino",
    "priority": "failures",
    "category": "failure",
    "track": "failures",
    "title": "Cascading Failure"
  },
  "bulkhead": {
    "lab": "state",
    "figure": "stateMachine",
    "priority": "failures",
    "category": "failure",
    "track": "failures",
    "title": "Bulkhead Isolation"
  },
  "circuit-breaker": {
    "lab": "state",
    "figure": "stateMachine",
    "priority": "gold",
    "category": "failure",
    "track": "failures",
    "title": "Circuit Breaker"
  },
  "fail-fast": {
    "lab": "state",
    "figure": "none",
    "priority": "failures",
    "category": "failure",
    "track": "failures",
    "title": "Fail Fast"
  },
  "graceful-degradation": {
    "lab": "state",
    "figure": "none",
    "priority": "failures",
    "category": "failure",
    "track": "failures",
    "title": "Graceful Degradation"
  },
  "brownout": {
    "lab": "state",
    "figure": "none",
    "priority": "failures",
    "category": "failure",
    "track": "failures",
    "title": "Brownout"
  },
  "connection-pool-exhaustion": {
    "lab": "metrics",
    "figure": "poolExhaustion",
    "priority": "failures",
    "category": "prod-eng",
    "track": "failures",
    "title": "Connection Pool Exhaustion"
  },
  "ephemeral-port-exhaustion": {
    "lab": "metrics",
    "figure": "none",
    "priority": "failures",
    "category": "prod-eng",
    "track": "failures",
    "title": "Ephemeral Port Exhaustion"
  },
  "n-plus-one": {
    "lab": "metrics",
    "figure": "fanOut",
    "priority": "failures",
    "category": "prod-eng",
    "track": "failures",
    "title": "N+1 Query Problem"
  },
  "slow-query-amplification": {
    "lab": "metrics",
    "figure": "none",
    "priority": "failures",
    "category": "prod-eng",
    "track": "failures",
    "title": "Slow Query Amplification"
  },
  "noisy-neighbor": {
    "lab": "metrics",
    "figure": "none",
    "priority": "failures",
    "category": "prod-eng",
    "track": "failures",
    "title": "Noisy Neighbor"
  },
  "priority-queue-starvation": {
    "lab": "metrics",
    "figure": "none",
    "priority": "failures",
    "category": "prod-eng",
    "track": "failures",
    "title": "Priority Queue Starvation"
  },
  "system-design-framework": {
    "lab": "none",
    "figure": "none",
    "priority": "hld",
    "category": "hld-foundations",
    "track": "hld",
    "title": "System Design Framework"
  },
  "requirements-gathering": {
    "lab": "none",
    "figure": "none",
    "priority": "hld",
    "category": "hld-foundations",
    "track": "hld",
    "title": "Requirements Gathering"
  },
  "non-functional-requirements": {
    "lab": "none",
    "figure": "none",
    "priority": "hld",
    "category": "hld-foundations",
    "track": "hld",
    "title": "Non-Functional Requirements"
  },
  "back-of-envelope-estimation": {
    "lab": "none",
    "figure": "none",
    "priority": "hld",
    "category": "hld-foundations",
    "track": "hld",
    "title": "Back-of-Envelope Estimation"
  },
  "qps-latency-storage-math": {
    "lab": "none",
    "figure": "comparison",
    "priority": "hld",
    "category": "hld-foundations",
    "track": "hld",
    "title": "QPS / Latency / Storage Math"
  },
  "sla-vs-slo": {
    "lab": "none",
    "figure": "comparison",
    "priority": "hld",
    "category": "hld-foundations",
    "track": "hld",
    "title": "SLA vs SLO"
  },
  "conways-law": {
    "lab": "none",
    "figure": "none",
    "priority": "hld",
    "category": "hld-foundations",
    "track": "hld",
    "title": "Conway's Law"
  },
  "technical-debt-vs-velocity": {
    "lab": "none",
    "figure": "none",
    "priority": "hld",
    "category": "hld-foundations",
    "track": "hld",
    "title": "Technical Debt vs Velocity"
  },
  "dns": {
    "lab": "clickFlow",
    "figure": "none",
    "priority": "gold",
    "category": "hld-networking",
    "track": "hld",
    "title": "DNS"
  },
  "tcp-udp-tradeoffs": {
    "lab": "none",
    "figure": "requestFlow",
    "priority": "hld",
    "category": "hld-networking",
    "track": "hld",
    "title": "TCP vs UDP"
  },
  "http-evolution": {
    "lab": "clickFlow",
    "figure": "none",
    "priority": "hld",
    "category": "hld-networking",
    "track": "hld",
    "title": "HTTP/1.1 → HTTP/2 → HTTP/3"
  },
  "grpc": {
    "lab": "clickFlow",
    "figure": "none",
    "priority": "hld",
    "category": "hld-networking",
    "track": "hld",
    "title": "gRPC"
  },
  "websockets": {
    "lab": "clickFlow",
    "figure": "none",
    "priority": "hld",
    "category": "hld-networking",
    "track": "hld",
    "title": "WebSockets"
  },
  "sse": {
    "lab": "none",
    "figure": "requestFlow",
    "priority": "hld",
    "category": "hld-networking",
    "track": "hld",
    "title": "Server-Sent Events"
  },
  "long-polling": {
    "lab": "none",
    "figure": "requestFlow",
    "priority": "hld",
    "category": "hld-networking",
    "track": "hld",
    "title": "Long Polling"
  },
  "webhooks": {
    "lab": "none",
    "figure": "requestFlow",
    "priority": "hld",
    "category": "hld-networking",
    "track": "hld",
    "title": "Webhooks"
  },
  "rest-vs-graphql": {
    "lab": "none",
    "figure": "requestFlow",
    "priority": "hld",
    "category": "hld-networking",
    "track": "hld",
    "title": "REST vs GraphQL"
  },
  "tls-termination": {
    "lab": "none",
    "figure": "requestFlow",
    "priority": "hld",
    "category": "hld-networking",
    "track": "hld",
    "title": "TLS Termination"
  },
  "load-balancer-l4-l7": {
    "lab": "architecture",
    "figure": "none",
    "priority": "hld",
    "category": "hld-blocks",
    "track": "hld",
    "title": "Load Balancer (L4 / L7)"
  },
  "reverse-proxy": {
    "lab": "architecture",
    "figure": "none",
    "priority": "hld",
    "category": "hld-blocks",
    "track": "hld",
    "title": "Reverse Proxy"
  },
  "api-gateway": {
    "lab": "architecture",
    "figure": "none",
    "priority": "hld",
    "category": "hld-blocks",
    "track": "hld",
    "title": "API Gateway"
  },
  "cdn": {
    "lab": "architecture",
    "figure": "none",
    "priority": "hld",
    "category": "hld-blocks",
    "track": "hld",
    "title": "CDN"
  },
  "caching-tiers": {
    "lab": "none",
    "figure": "requestFlow",
    "priority": "hld",
    "category": "hld-blocks",
    "track": "hld",
    "title": "Caching Tiers"
  },
  "sql-vs-nosql-selection": {
    "lab": "none",
    "figure": "requestFlow",
    "priority": "hld",
    "category": "hld-blocks",
    "track": "hld",
    "title": "SQL vs NoSQL Selection"
  },
  "partitioning-schemes": {
    "lab": "none",
    "figure": "requestFlow",
    "priority": "hld",
    "category": "hld-blocks",
    "track": "hld",
    "title": "Partitioning Schemes"
  },
  "replication-topologies": {
    "lab": "none",
    "figure": "requestFlow",
    "priority": "hld",
    "category": "hld-blocks",
    "track": "hld",
    "title": "Replication Topologies"
  },
  "message-queues": {
    "lab": "architecture",
    "figure": "none",
    "priority": "hld",
    "category": "hld-blocks",
    "track": "hld",
    "title": "Message Queues"
  },
  "kafka-vs-rabbitmq": {
    "lab": "none",
    "figure": "requestFlow",
    "priority": "hld",
    "category": "hld-blocks",
    "track": "hld",
    "title": "Kafka vs RabbitMQ"
  },
  "pub-sub-fanout": {
    "lab": "none",
    "figure": "requestFlow",
    "priority": "hld",
    "category": "hld-blocks",
    "track": "hld",
    "title": "Pub/Sub Fan-out"
  },
  "edge-rate-limiting": {
    "lab": "none",
    "figure": "requestFlow",
    "priority": "hld",
    "category": "hld-blocks",
    "track": "hld",
    "title": "Edge Rate Limiting"
  },
  "service-discovery": {
    "lab": "none",
    "figure": "requestFlow",
    "priority": "hld",
    "category": "hld-blocks",
    "track": "hld",
    "title": "Service Discovery"
  },
  "service-mesh": {
    "lab": "architecture",
    "figure": "none",
    "priority": "hld",
    "category": "hld-blocks",
    "track": "hld",
    "title": "Service Mesh"
  },
  "blob-storage": {
    "lab": "none",
    "figure": "requestFlow",
    "priority": "hld",
    "category": "hld-blocks",
    "track": "hld",
    "title": "Blob Storage"
  },
  "edge-compute": {
    "lab": "none",
    "figure": "requestFlow",
    "priority": "hld",
    "category": "hld-blocks",
    "track": "hld",
    "title": "Edge Compute"
  },
  "consensus-raft-paxos": {
    "lab": "state",
    "figure": "consensus",
    "priority": "hld",
    "category": "hld-theory",
    "track": "hld",
    "title": "Consensus (Raft / Paxos)"
  },
  "linearizability-vs-serializability": {
    "lab": "none",
    "figure": "comparison",
    "priority": "hld",
    "category": "hld-theory",
    "track": "hld",
    "title": "Linearizability vs Serializability"
  },
  "quorum-reads-writes": {
    "lab": "state",
    "figure": "quorum",
    "priority": "hld",
    "category": "hld-theory",
    "track": "hld",
    "title": "Quorum Reads / Writes"
  },
  "cap-theorem-framing": {
    "lab": "state",
    "figure": "none",
    "priority": "hld",
    "category": "hld-theory",
    "track": "hld",
    "title": "CAP Theorem (HLD framing)"
  },
  "pacelc": {
    "lab": "state",
    "figure": "none",
    "priority": "hld",
    "category": "hld-theory",
    "track": "hld",
    "title": "PACELC"
  },
  "hybrid-logical-clocks": {
    "lab": "none",
    "figure": "none",
    "priority": "hld",
    "category": "hld-theory",
    "track": "hld",
    "title": "Hybrid Logical Clocks"
  },
  "crdt-overview": {
    "lab": "none",
    "figure": "none",
    "priority": "hld",
    "category": "hld-theory",
    "track": "hld",
    "title": "CRDT Overview"
  },
  "distributed-transactions-comparison": {
    "lab": "none",
    "figure": "comparison",
    "priority": "hld",
    "category": "hld-theory",
    "track": "hld",
    "title": "Distributed Transactions"
  },
  "exactly-once-honesty": {
    "lab": "none",
    "figure": "none",
    "priority": "hld",
    "category": "hld-theory",
    "track": "hld",
    "title": "Exactly-Once Honesty"
  },
  "phi-accrual-failure-detection": {
    "lab": "none",
    "figure": "none",
    "priority": "hld",
    "category": "hld-theory",
    "track": "hld",
    "title": "Phi Accrual Failure Detection"
  },
  "consistent-hashing-placement": {
    "lab": "algorithm",
    "figure": "hashRing",
    "priority": "hld",
    "category": "hld-theory",
    "track": "hld",
    "title": "Consistent Hashing (placement)"
  },
  "merkle-anti-entropy": {
    "lab": "none",
    "figure": "none",
    "priority": "hld",
    "category": "hld-theory",
    "track": "hld",
    "title": "Merkle Anti-Entropy"
  },
  "btree-vs-lsm": {
    "lab": "none",
    "figure": "comparison",
    "priority": "hld",
    "category": "hld-data",
    "track": "hld",
    "title": "B-Tree vs LSM"
  },
  "oltp-vs-olap": {
    "lab": "none",
    "figure": "comparison",
    "priority": "hld",
    "category": "hld-data",
    "track": "hld",
    "title": "OLTP vs OLAP"
  },
  "warehouse-lake-lakehouse": {
    "lab": "none",
    "figure": "comparison",
    "priority": "hld",
    "category": "hld-data",
    "track": "hld",
    "title": "Warehouse vs Lake vs Lakehouse"
  },
  "lambda-vs-kappa": {
    "lab": "none",
    "figure": "comparison",
    "priority": "hld",
    "category": "hld-data",
    "track": "hld",
    "title": "Lambda vs Kappa"
  },
  "cdc": {
    "lab": "none",
    "figure": "none",
    "priority": "hld",
    "category": "hld-data",
    "track": "hld",
    "title": "Change Data Capture"
  },
  "search-inverted-index": {
    "lab": "none",
    "figure": "none",
    "priority": "hld",
    "category": "hld-data",
    "track": "hld",
    "title": "Search / Inverted Index"
  },
  "time-series-db": {
    "lab": "none",
    "figure": "none",
    "priority": "hld",
    "category": "hld-data",
    "track": "hld",
    "title": "Time-Series DB"
  },
  "graph-db": {
    "lab": "none",
    "figure": "none",
    "priority": "hld",
    "category": "hld-data",
    "track": "hld",
    "title": "Graph DB"
  },
  "vector-db-ann": {
    "lab": "none",
    "figure": "none",
    "priority": "hld",
    "category": "hld-data",
    "track": "hld",
    "title": "Vector DB / ANN"
  },
  "key-value-stores": {
    "lab": "none",
    "figure": "none",
    "priority": "hld",
    "category": "hld-data",
    "track": "hld",
    "title": "Key-Value Stores"
  },
  "materialized-views": {
    "lab": "none",
    "figure": "none",
    "priority": "hld",
    "category": "hld-data",
    "track": "hld",
    "title": "Materialized Views"
  },
  "stream-table-duality": {
    "lab": "none",
    "figure": "none",
    "priority": "hld",
    "category": "hld-data",
    "track": "hld",
    "title": "Stream-Table Duality"
  },
  "monolith-vs-microservices": {
    "lab": "none",
    "figure": "architecture",
    "priority": "hld",
    "category": "hld-architecture",
    "track": "hld",
    "title": "Monolith vs Microservices"
  },
  "event-driven-architecture": {
    "lab": "none",
    "figure": "architecture",
    "priority": "hld",
    "category": "hld-architecture",
    "track": "hld",
    "title": "Event-Driven Architecture"
  },
  "cqrs": {
    "lab": "none",
    "figure": "architecture",
    "priority": "hld",
    "category": "hld-architecture",
    "track": "hld",
    "title": "CQRS"
  },
  "event-sourcing": {
    "lab": "none",
    "figure": "architecture",
    "priority": "hld",
    "category": "hld-architecture",
    "track": "hld",
    "title": "Event Sourcing"
  },
  "serverless-faas": {
    "lab": "none",
    "figure": "architecture",
    "priority": "hld",
    "category": "hld-architecture",
    "track": "hld",
    "title": "Serverless / FaaS"
  },
  "bff": {
    "lab": "none",
    "figure": "architecture",
    "priority": "hld",
    "category": "hld-architecture",
    "track": "hld",
    "title": "Backend for Frontend"
  },
  "strangler-fig": {
    "lab": "none",
    "figure": "architecture",
    "priority": "hld",
    "category": "hld-architecture",
    "track": "hld",
    "title": "Strangler Fig"
  },
  "hexagonal-clean-architecture": {
    "lab": "none",
    "figure": "architecture",
    "priority": "hld",
    "category": "hld-architecture",
    "track": "hld",
    "title": "Hexagonal / Clean Architecture"
  },
  "anti-corruption-layer": {
    "lab": "none",
    "figure": "architecture",
    "priority": "hld",
    "category": "hld-architecture",
    "track": "hld",
    "title": "Anti-Corruption Layer"
  },
  "multi-region-active-active": {
    "lab": "none",
    "figure": "architecture",
    "priority": "hld",
    "category": "hld-architecture",
    "track": "hld",
    "title": "Multi-Region Active-Active"
  },
  "multi-tenancy-patterns": {
    "lab": "none",
    "figure": "architecture",
    "priority": "hld",
    "category": "hld-architecture",
    "track": "hld",
    "title": "Multi-Tenancy Patterns"
  },
  "local-first-crdt-apps": {
    "lab": "none",
    "figure": "architecture",
    "priority": "hld",
    "category": "hld-architecture",
    "track": "hld",
    "title": "Local-First / CRDT Apps"
  },
  "cell-architecture-design": {
    "lab": "none",
    "figure": "architecture",
    "priority": "hld",
    "category": "hld-architecture",
    "track": "hld",
    "title": "Cell Architecture (design)"
  },
  "scatter-gather": {
    "lab": "none",
    "figure": "architecture",
    "priority": "hld",
    "category": "hld-architecture",
    "track": "hld",
    "title": "Scatter-Gather"
  },
  "observability-three-pillars": {
    "lab": "none",
    "figure": "requestFlow",
    "priority": "hld",
    "category": "hld-reliability",
    "track": "hld",
    "title": "Observability Pillars"
  },
  "sli-slo-error-budgets": {
    "lab": "none",
    "figure": "requestFlow",
    "priority": "hld",
    "category": "hld-reliability",
    "track": "hld",
    "title": "SLI / SLO / Error Budgets"
  },
  "resilience-patterns-overview": {
    "lab": "none",
    "figure": "requestFlow",
    "priority": "hld",
    "category": "hld-reliability",
    "track": "hld",
    "title": "Resilience Patterns Overview"
  },
  "graceful-degradation-hld": {
    "lab": "none",
    "figure": "requestFlow",
    "priority": "hld",
    "category": "hld-reliability",
    "track": "hld",
    "title": "Graceful Degradation"
  },
  "autoscaling-hpa": {
    "lab": "none",
    "figure": "requestFlow",
    "priority": "hld",
    "category": "hld-reliability",
    "track": "hld",
    "title": "Autoscaling / HPA"
  },
  "deploy-strategies": {
    "lab": "none",
    "figure": "requestFlow",
    "priority": "hld",
    "category": "hld-reliability",
    "track": "hld",
    "title": "Deploy Strategies"
  },
  "chaos-engineering": {
    "lab": "none",
    "figure": "requestFlow",
    "priority": "hld",
    "category": "hld-reliability",
    "track": "hld",
    "title": "Chaos Engineering"
  },
  "incident-response": {
    "lab": "none",
    "figure": "requestFlow",
    "priority": "hld",
    "category": "hld-reliability",
    "track": "hld",
    "title": "Incident Response"
  },
  "health-probes": {
    "lab": "none",
    "figure": "requestFlow",
    "priority": "hld",
    "category": "hld-reliability",
    "track": "hld",
    "title": "Health / Readiness / Liveness"
  },
  "finops": {
    "lab": "none",
    "figure": "requestFlow",
    "priority": "hld",
    "category": "hld-reliability",
    "track": "hld",
    "title": "FinOps"
  },
  "platform-engineering-idp": {
    "lab": "none",
    "figure": "requestFlow",
    "priority": "hld",
    "category": "hld-reliability",
    "track": "hld",
    "title": "Platform Engineering / IDP"
  },
  "poison-pill-handling": {
    "lab": "none",
    "figure": "requestFlow",
    "priority": "hld",
    "category": "hld-reliability",
    "track": "hld",
    "title": "Poison Pill Handling"
  },
  "authn-vs-authz": {
    "lab": "none",
    "figure": "requestFlow",
    "priority": "hld",
    "category": "hld-security",
    "track": "hld",
    "title": "AuthN vs AuthZ"
  },
  "oauth2-oidc": {
    "lab": "none",
    "figure": "requestFlow",
    "priority": "hld",
    "category": "hld-security",
    "track": "hld",
    "title": "OAuth2 / OIDC"
  },
  "jwt-pitfalls": {
    "lab": "none",
    "figure": "requestFlow",
    "priority": "hld",
    "category": "hld-security",
    "track": "hld",
    "title": "JWT Pitfalls"
  },
  "mtls-service-identity": {
    "lab": "none",
    "figure": "requestFlow",
    "priority": "hld",
    "category": "hld-security",
    "track": "hld",
    "title": "mTLS / Service Identity"
  },
  "secrets-management": {
    "lab": "none",
    "figure": "requestFlow",
    "priority": "hld",
    "category": "hld-security",
    "track": "hld",
    "title": "Secrets Management"
  },
  "ddos-mitigation": {
    "lab": "none",
    "figure": "requestFlow",
    "priority": "hld",
    "category": "hld-security",
    "track": "hld",
    "title": "DDoS Mitigation"
  },
  "waf": {
    "lab": "none",
    "figure": "requestFlow",
    "priority": "hld",
    "category": "hld-security",
    "track": "hld",
    "title": "WAF"
  },
  "zero-trust-perimeter": {
    "lab": "none",
    "figure": "requestFlow",
    "priority": "hld",
    "category": "hld-security",
    "track": "hld",
    "title": "Zero-Trust Perimeter"
  },
  "strong-vs-eventual-consistency": {
    "lab": "none",
    "figure": "comparison",
    "priority": "hld",
    "category": "hld-tradeoffs",
    "track": "hld",
    "title": "Strong vs Eventual Consistency"
  },
  "acid-vs-base": {
    "lab": "none",
    "figure": "comparison",
    "priority": "hld",
    "category": "hld-tradeoffs",
    "track": "hld",
    "title": "ACID vs BASE"
  },
  "sql-vs-nosql": {
    "lab": "none",
    "figure": "comparison",
    "priority": "hld",
    "category": "hld-tradeoffs",
    "track": "hld",
    "title": "SQL vs NoSQL"
  },
  "latency-vs-throughput": {
    "lab": "none",
    "figure": "comparison",
    "priority": "hld",
    "category": "hld-tradeoffs",
    "track": "hld",
    "title": "Latency vs Throughput"
  },
  "cache-strategies": {
    "lab": "none",
    "figure": "comparison",
    "priority": "hld",
    "category": "hld-tradeoffs",
    "track": "hld",
    "title": "Cache Strategies"
  },
  "batch-vs-stream": {
    "lab": "none",
    "figure": "comparison",
    "priority": "hld",
    "category": "hld-tradeoffs",
    "track": "hld",
    "title": "Batch vs Stream"
  },
  "lb-vs-proxy-vs-gateway": {
    "lab": "none",
    "figure": "comparison",
    "priority": "hld",
    "category": "hld-tradeoffs",
    "track": "hld",
    "title": "LB vs Proxy vs Gateway"
  },
  "rest-vs-grpc-vs-graphql": {
    "lab": "none",
    "figure": "comparison",
    "priority": "hld",
    "category": "hld-tradeoffs",
    "track": "hld",
    "title": "REST vs gRPC vs GraphQL"
  },
  "polling-vs-websocket-family": {
    "lab": "none",
    "figure": "comparison",
    "priority": "hld",
    "category": "hld-tradeoffs",
    "track": "hld",
    "title": "Polling vs WebSocket Family"
  },
  "rate-limit-algorithms": {
    "lab": "none",
    "figure": "comparison",
    "priority": "hld",
    "category": "hld-tradeoffs",
    "track": "hld",
    "title": "Rate-Limit Algorithms"
  },
  "partitioning-schemes-tradeoff": {
    "lab": "none",
    "figure": "comparison",
    "priority": "hld",
    "category": "hld-tradeoffs",
    "track": "hld",
    "title": "Partitioning Schemes"
  },
  "replication-topologies-tradeoff": {
    "lab": "none",
    "figure": "comparison",
    "priority": "hld",
    "category": "hld-tradeoffs",
    "track": "hld",
    "title": "Replication Topologies"
  },
  "two-pc-vs-saga-vs-tcc": {
    "lab": "none",
    "figure": "comparison",
    "priority": "hld",
    "category": "hld-tradeoffs",
    "track": "hld",
    "title": "2PC vs Saga vs TCC"
  },
  "push-vs-pull": {
    "lab": "none",
    "figure": "comparison",
    "priority": "hld",
    "category": "hld-tradeoffs",
    "track": "hld",
    "title": "Push vs Pull"
  },
  "lambda-vs-kappa-tradeoff": {
    "lab": "none",
    "figure": "comparison",
    "priority": "hld",
    "category": "hld-tradeoffs",
    "track": "hld",
    "title": "Lambda vs Kappa"
  },
  "vertical-vs-horizontal-scale": {
    "lab": "none",
    "figure": "comparison",
    "priority": "hld",
    "category": "hld-tradeoffs",
    "track": "hld",
    "title": "Vertical vs Horizontal Scale"
  },
  "normalization-vs-denormalization": {
    "lab": "none",
    "figure": "comparison",
    "priority": "hld",
    "category": "hld-tradeoffs",
    "track": "hld",
    "title": "Normalization vs Denormalization"
  },
  "single-vs-multi-region": {
    "lab": "none",
    "figure": "comparison",
    "priority": "hld",
    "category": "hld-tradeoffs",
    "track": "hld",
    "title": "Single vs Multi-Region"
  },
  "sync-vs-async-communication": {
    "lab": "none",
    "figure": "comparison",
    "priority": "hld",
    "category": "hld-tradeoffs",
    "track": "hld",
    "title": "Sync vs Async Communication"
  },
  "stateful-vs-stateless": {
    "lab": "none",
    "figure": "comparison",
    "priority": "hld",
    "category": "hld-tradeoffs",
    "track": "hld",
    "title": "Stateful vs Stateless Services"
  },
  "pessimistic-vs-optimistic-concurrency": {
    "lab": "none",
    "figure": "comparison",
    "priority": "hld",
    "category": "hld-tradeoffs",
    "track": "hld",
    "title": "Pessimistic vs Optimistic"
  },
  "managed-vs-self-hosted": {
    "lab": "none",
    "figure": "comparison",
    "priority": "hld",
    "category": "hld-tradeoffs",
    "track": "hld",
    "title": "Managed vs Self-Hosted"
  },
  "url-shortener": {
    "lab": "architecture",
    "figure": "none",
    "priority": "hld",
    "category": "hld-classics",
    "track": "hld",
    "title": "URL Shortener"
  },
  "rate-limiter-service": {
    "lab": "architecture",
    "figure": "none",
    "priority": "hld",
    "category": "hld-classics",
    "track": "hld",
    "title": "Rate Limiter Service"
  },
  "news-feed": {
    "lab": "architecture",
    "figure": "none",
    "priority": "hld",
    "category": "hld-classics",
    "track": "hld",
    "title": "News Feed"
  },
  "notification-system": {
    "lab": "none",
    "figure": "architecture",
    "priority": "hld",
    "category": "hld-classics",
    "track": "hld",
    "title": "Notification System"
  },
  "chat-system": {
    "lab": "architecture",
    "figure": "none",
    "priority": "hld",
    "category": "hld-classics",
    "track": "hld",
    "title": "Chat System"
  },
  "file-storage-s3": {
    "lab": "none",
    "figure": "architecture",
    "priority": "hld",
    "category": "hld-classics",
    "track": "hld",
    "title": "File Storage (S3-like)"
  },
  "search-autocomplete": {
    "lab": "none",
    "figure": "architecture",
    "priority": "hld",
    "category": "hld-classics",
    "track": "hld",
    "title": "Search Autocomplete"
  },
  "distributed-cache-design": {
    "lab": "none",
    "figure": "architecture",
    "priority": "hld",
    "category": "hld-classics",
    "track": "hld",
    "title": "Distributed Cache Design"
  },
  "payment-system-hld": {
    "lab": "architecture",
    "figure": "none",
    "priority": "hld",
    "category": "hld-classics",
    "track": "hld",
    "title": "Payment System (HLD)"
  },
  "ride-sharing-dispatch": {
    "lab": "none",
    "figure": "architecture",
    "priority": "hld",
    "category": "hld-classics",
    "track": "hld",
    "title": "Ride-Sharing Dispatch"
  },
  "ticket-booking": {
    "lab": "architecture",
    "figure": "none",
    "priority": "hld",
    "category": "hld-classics",
    "track": "hld",
    "title": "Ticket Booking"
  },
  "video-streaming": {
    "lab": "none",
    "figure": "architecture",
    "priority": "hld",
    "category": "hld-classics",
    "track": "hld",
    "title": "Video Streaming"
  },
  "metrics-monitoring-system": {
    "lab": "none",
    "figure": "architecture",
    "priority": "hld",
    "category": "hld-classics",
    "track": "hld",
    "title": "Metrics / Monitoring System"
  },
  "distributed-cron": {
    "lab": "none",
    "figure": "architecture",
    "priority": "hld",
    "category": "hld-classics",
    "track": "hld",
    "title": "Distributed Cron"
  },
  "leaderboard": {
    "lab": "none",
    "figure": "architecture",
    "priority": "hld",
    "category": "hld-classics",
    "track": "hld",
    "title": "Leaderboard"
  },
  "collaborative-editor": {
    "lab": "none",
    "figure": "architecture",
    "priority": "hld",
    "category": "hld-classics",
    "track": "hld",
    "title": "Collaborative Editor"
  },
  "cap-theorem": {
    "lab": "clickFlow",
    "figure": "none",
    "priority": "hld",
    "category": "hld-consistency",
    "track": "hld",
    "title": "CAP Theorem"
  },
  "eventual-consistency": {
    "lab": "clickFlow",
    "figure": "none",
    "priority": "hld",
    "category": "hld-consistency",
    "track": "hld",
    "title": "Eventual Consistency"
  },
  "read-your-writes": {
    "lab": "clickFlow",
    "figure": "none",
    "priority": "gold",
    "category": "hld-consistency",
    "track": "hld",
    "title": "Read Your Writes"
  },
  "monotonic-reads": {
    "lab": "clickFlow",
    "figure": "none",
    "priority": "hld",
    "category": "hld-consistency",
    "track": "hld",
    "title": "Monotonic Reads"
  },
  "session-consistency": {
    "lab": "clickFlow",
    "figure": "none",
    "priority": "hld",
    "category": "hld-consistency",
    "track": "hld",
    "title": "Session Consistency"
  },
  "quorum": {
    "lab": "clickFlow",
    "figure": "quorum",
    "priority": "hld",
    "category": "hld-consistency",
    "track": "hld",
    "title": "Quorum"
  },
  "crdt": {
    "lab": "clickFlow",
    "figure": "none",
    "priority": "hld",
    "category": "hld-consistency",
    "track": "hld",
    "title": "CRDT"
  },
  "hot-partition": {
    "lab": "algorithm",
    "figure": "none",
    "priority": "hld",
    "category": "hld-db-scaling",
    "track": "hld",
    "title": "Hot Partition"
  },
  "hot-row": {
    "lab": "algorithm",
    "figure": "none",
    "priority": "hld",
    "category": "hld-db-scaling",
    "track": "hld",
    "title": "Hot Row"
  },
  "hot-index": {
    "lab": "algorithm",
    "figure": "none",
    "priority": "hld",
    "category": "hld-db-scaling",
    "track": "hld",
    "title": "Hot Index"
  },
  "secondary-index-lag": {
    "lab": "algorithm",
    "figure": "none",
    "priority": "hld",
    "category": "hld-db-scaling",
    "track": "hld",
    "title": "Secondary Index Lag"
  },
  "read-replica-lag": {
    "lab": "algorithm",
    "figure": "none",
    "priority": "hld",
    "category": "hld-db-scaling",
    "track": "hld",
    "title": "Read Replica Lag"
  },
  "split-brain": {
    "lab": "algorithm",
    "figure": "none",
    "priority": "hld",
    "category": "hld-db-scaling",
    "track": "hld",
    "title": "Split Brain"
  },
  "shard-rebalancing": {
    "lab": "algorithm",
    "figure": "none",
    "priority": "hld",
    "category": "hld-db-scaling",
    "track": "hld",
    "title": "Shard Rebalancing"
  },
  "consistent-hashing": {
    "lab": "algorithm",
    "figure": "hashRing",
    "priority": "hld",
    "category": "hld-db-scaling",
    "track": "hld",
    "title": "Consistent Hashing"
  },
  "cross-shard-txn": {
    "lab": "algorithm",
    "figure": "none",
    "priority": "hld",
    "category": "hld-db-scaling",
    "track": "hld",
    "title": "Cross-Shard Transaction"
  },
  "tail-latency": {
    "lab": "metrics",
    "figure": "none",
    "priority": "hld",
    "category": "hld-performance",
    "track": "hld",
    "title": "Tail Latency"
  },
  "queue-buildup": {
    "lab": "metrics",
    "figure": "none",
    "priority": "hld",
    "category": "hld-performance",
    "track": "hld",
    "title": "Queue Buildup"
  },
  "littles-law": {
    "lab": "metrics",
    "figure": "none",
    "priority": "hld",
    "category": "hld-performance",
    "track": "hld",
    "title": "Little's Law"
  },
  "coordinated-omission-perf": {
    "lab": "metrics",
    "figure": "none",
    "priority": "hld",
    "category": "hld-performance",
    "track": "hld",
    "title": "Coordinated Omission"
  },
  "false-sharing": {
    "lab": "metrics",
    "figure": "none",
    "priority": "hld",
    "category": "hld-performance",
    "track": "hld",
    "title": "False Sharing"
  },
  "numa": {
    "lab": "metrics",
    "figure": "none",
    "priority": "hld",
    "category": "hld-performance",
    "track": "hld",
    "title": "NUMA Effects"
  },
  "context-switching": {
    "lab": "metrics",
    "figure": "none",
    "priority": "hld",
    "category": "hld-performance",
    "track": "hld",
    "title": "Context Switching"
  },
  "gc-pause": {
    "lab": "metrics",
    "figure": "none",
    "priority": "hld",
    "category": "hld-performance",
    "track": "hld",
    "title": "GC Pause"
  },
  "write-through": {
    "lab": "clickFlow",
    "figure": "none",
    "priority": "hld",
    "category": "hld-cache-strategies",
    "track": "hld",
    "title": "Write Through"
  },
  "write-around": {
    "lab": "clickFlow",
    "figure": "none",
    "priority": "hld",
    "category": "hld-cache-strategies",
    "track": "hld",
    "title": "Write Around"
  },
  "write-back": {
    "lab": "clickFlow",
    "figure": "none",
    "priority": "hld",
    "category": "hld-cache-strategies",
    "track": "hld",
    "title": "Write Back"
  },
  "read-through": {
    "lab": "clickFlow",
    "figure": "none",
    "priority": "hld",
    "category": "hld-cache-strategies",
    "track": "hld",
    "title": "Read Through"
  },
  "cache-aside": {
    "lab": "clickFlow",
    "figure": "none",
    "priority": "hld",
    "category": "hld-cache-strategies",
    "track": "hld",
    "title": "Cache Aside"
  },
  "negative-cache": {
    "lab": "clickFlow",
    "figure": "none",
    "priority": "hld",
    "category": "hld-cache-strategies",
    "track": "hld",
    "title": "Negative Cache"
  },
  "hedged-requests": {
    "lab": "metrics",
    "figure": "none",
    "priority": "hld",
    "category": "hld-rate-limiting",
    "track": "hld",
    "title": "Hedged Requests"
  },
  "request-coalescing": {
    "lab": "metrics",
    "figure": "none",
    "priority": "hld",
    "category": "hld-rate-limiting",
    "track": "hld",
    "title": "Request Coalescing"
  },
  "token-bucket": {
    "lab": "metrics",
    "figure": "none",
    "priority": "gold",
    "category": "hld-rate-limiting",
    "track": "hld",
    "title": "Token Bucket"
  },
  "leaky-bucket": {
    "lab": "metrics",
    "figure": "none",
    "priority": "gold",
    "category": "hld-rate-limiting",
    "track": "hld",
    "title": "Leaky Bucket"
  },
  "adaptive-concurrency": {
    "lab": "metrics",
    "figure": "none",
    "priority": "hld",
    "category": "hld-rate-limiting",
    "track": "hld",
    "title": "Adaptive Concurrency Control"
  },
  "load-shedding": {
    "lab": "metrics",
    "figure": "none",
    "priority": "hld",
    "category": "hld-rate-limiting",
    "track": "hld",
    "title": "Load Shedding"
  },
  "admission-control": {
    "lab": "metrics",
    "figure": "none",
    "priority": "hld",
    "category": "hld-rate-limiting",
    "track": "hld",
    "title": "Admission Control"
  },
  "shuffle-sharding": {
    "lab": "metrics",
    "figure": "none",
    "priority": "hld",
    "category": "hld-rate-limiting",
    "track": "hld",
    "title": "Shuffle Sharding"
  },
  "cell-architecture": {
    "lab": "none",
    "figure": "architecture",
    "priority": "hld",
    "category": "hld-rate-limiting",
    "track": "hld",
    "title": "Cell Architecture"
  },
  "sticky-sessions": {
    "lab": "metrics",
    "figure": "none",
    "priority": "hld",
    "category": "hld-rate-limiting",
    "track": "hld",
    "title": "Sticky Sessions"
  },
  "watermarking": {
    "lab": "metrics",
    "figure": "none",
    "priority": "hld",
    "category": "hld-rate-limiting",
    "track": "hld",
    "title": "Watermarking"
  },
  "gossip-protocols": {
    "lab": "none",
    "figure": "architecture",
    "priority": "hld",
    "category": "hld-rate-limiting",
    "track": "hld",
    "title": "Gossip Protocols"
  },
  "dead-letter-queue": {
    "lab": "queue",
    "figure": "none",
    "priority": "gold",
    "category": "hld-messaging-ops",
    "track": "hld",
    "title": "Dead Letter Queue"
  },
  "visibility-timeout": {
    "lab": "queue",
    "figure": "none",
    "priority": "hld",
    "category": "hld-messaging-ops",
    "track": "hld",
    "title": "Visibility Timeout"
  },
  "consumer-rebalancing": {
    "lab": "queue",
    "figure": "none",
    "priority": "hld",
    "category": "hld-messaging-ops",
    "track": "hld",
    "title": "Consumer Group Rebalancing"
  },
  "exponential-backoff": {
    "lab": "metrics",
    "figure": "none",
    "priority": "hld",
    "category": "hld-reliability-patterns",
    "track": "hld",
    "title": "Exponential Backoff + Jitter"
  },
  "encapsulation": {
    "lab": "none",
    "figure": "umlClass",
    "priority": "lld",
    "category": "lld-oop",
    "track": "lld",
    "title": "Encapsulation"
  },
  "abstraction": {
    "lab": "none",
    "figure": "umlClass",
    "priority": "lld",
    "category": "lld-oop",
    "track": "lld",
    "title": "Abstraction"
  },
  "inheritance-pitfalls": {
    "lab": "none",
    "figure": "umlClass",
    "priority": "lld",
    "category": "lld-oop",
    "track": "lld",
    "title": "Inheritance Pitfalls"
  },
  "polymorphism": {
    "lab": "none",
    "figure": "umlClass",
    "priority": "lld",
    "category": "lld-oop",
    "track": "lld",
    "title": "Polymorphism"
  },
  "composition-over-inheritance": {
    "lab": "none",
    "figure": "umlClass",
    "priority": "lld",
    "category": "lld-oop",
    "track": "lld",
    "title": "Composition over Inheritance"
  },
  "single-responsibility-principle": {
    "lab": "none",
    "figure": "umlClass",
    "priority": "lld",
    "category": "lld-oop",
    "track": "lld",
    "title": "Single Responsibility"
  },
  "open-closed-principle": {
    "lab": "none",
    "figure": "umlClass",
    "priority": "lld",
    "category": "lld-oop",
    "track": "lld",
    "title": "Open/Closed Principle"
  },
  "liskov-substitution-principle": {
    "lab": "none",
    "figure": "umlClass",
    "priority": "lld",
    "category": "lld-oop",
    "track": "lld",
    "title": "Liskov Substitution"
  },
  "interface-segregation-principle": {
    "lab": "none",
    "figure": "umlClass",
    "priority": "lld",
    "category": "lld-oop",
    "track": "lld",
    "title": "Interface Segregation"
  },
  "dependency-inversion-principle": {
    "lab": "none",
    "figure": "umlClass",
    "priority": "lld",
    "category": "lld-oop",
    "track": "lld",
    "title": "Dependency Inversion"
  },
  "dry-principle": {
    "lab": "none",
    "figure": "none",
    "priority": "lld",
    "category": "lld-oop",
    "track": "lld",
    "title": "DRY"
  },
  "kiss-yagni-principles": {
    "lab": "none",
    "figure": "none",
    "priority": "lld",
    "category": "lld-oop",
    "track": "lld",
    "title": "KISS & YAGNI"
  },
  "singleton": {
    "lab": "clickFlow",
    "figure": "umlClass",
    "priority": "lld",
    "category": "lld-creational",
    "track": "lld",
    "title": "Singleton"
  },
  "factory-method": {
    "lab": "none",
    "figure": "umlClass",
    "priority": "lld",
    "category": "lld-creational",
    "track": "lld",
    "title": "Factory Method"
  },
  "abstract-factory": {
    "lab": "none",
    "figure": "umlClass",
    "priority": "lld",
    "category": "lld-creational",
    "track": "lld",
    "title": "Abstract Factory"
  },
  "builder": {
    "lab": "none",
    "figure": "umlClass",
    "priority": "lld",
    "category": "lld-creational",
    "track": "lld",
    "title": "Builder"
  },
  "prototype": {
    "lab": "none",
    "figure": "umlClass",
    "priority": "lld",
    "category": "lld-creational",
    "track": "lld",
    "title": "Prototype"
  },
  "object-pool": {
    "lab": "none",
    "figure": "umlClass",
    "priority": "lld",
    "category": "lld-creational",
    "track": "lld",
    "title": "Object Pool"
  },
  "dependency-injection": {
    "lab": "none",
    "figure": "umlClass",
    "priority": "lld",
    "category": "lld-creational",
    "track": "lld",
    "title": "Dependency Injection"
  },
  "adapter": {
    "lab": "none",
    "figure": "umlClass",
    "priority": "lld",
    "category": "lld-structural",
    "track": "lld",
    "title": "Adapter"
  },
  "bridge": {
    "lab": "none",
    "figure": "umlClass",
    "priority": "lld",
    "category": "lld-structural",
    "track": "lld",
    "title": "Bridge"
  },
  "composite": {
    "lab": "none",
    "figure": "umlClass",
    "priority": "lld",
    "category": "lld-structural",
    "track": "lld",
    "title": "Composite"
  },
  "decorator": {
    "lab": "none",
    "figure": "umlClass",
    "priority": "lld",
    "category": "lld-structural",
    "track": "lld",
    "title": "Decorator"
  },
  "facade": {
    "lab": "none",
    "figure": "umlClass",
    "priority": "lld",
    "category": "lld-structural",
    "track": "lld",
    "title": "Facade"
  },
  "flyweight": {
    "lab": "none",
    "figure": "umlClass",
    "priority": "lld",
    "category": "lld-structural",
    "track": "lld",
    "title": "Flyweight"
  },
  "proxy": {
    "lab": "none",
    "figure": "umlClass",
    "priority": "lld",
    "category": "lld-structural",
    "track": "lld",
    "title": "Proxy"
  },
  "module-pattern": {
    "lab": "none",
    "figure": "none",
    "priority": "lld",
    "category": "lld-structural",
    "track": "lld",
    "title": "Module Pattern"
  },
  "strategy": {
    "lab": "clickFlow",
    "figure": "none",
    "priority": "lld",
    "category": "lld-behavioral",
    "track": "lld",
    "title": "Strategy"
  },
  "observer": {
    "lab": "clickFlow",
    "figure": "none",
    "priority": "lld",
    "category": "lld-behavioral",
    "track": "lld",
    "title": "Observer"
  },
  "command": {
    "lab": "none",
    "figure": "umlClass",
    "priority": "lld",
    "category": "lld-behavioral",
    "track": "lld",
    "title": "Command"
  },
  "state": {
    "lab": "clickFlow",
    "figure": "none",
    "priority": "lld",
    "category": "lld-behavioral",
    "track": "lld",
    "title": "State"
  },
  "template-method": {
    "lab": "none",
    "figure": "umlClass",
    "priority": "lld",
    "category": "lld-behavioral",
    "track": "lld",
    "title": "Template Method"
  },
  "iterator": {
    "lab": "none",
    "figure": "umlClass",
    "priority": "lld",
    "category": "lld-behavioral",
    "track": "lld",
    "title": "Iterator"
  },
  "chain-of-responsibility": {
    "lab": "none",
    "figure": "umlClass",
    "priority": "lld",
    "category": "lld-behavioral",
    "track": "lld",
    "title": "Chain of Responsibility"
  },
  "mediator": {
    "lab": "none",
    "figure": "umlClass",
    "priority": "lld",
    "category": "lld-behavioral",
    "track": "lld",
    "title": "Mediator"
  },
  "memento": {
    "lab": "none",
    "figure": "umlClass",
    "priority": "lld",
    "category": "lld-behavioral",
    "track": "lld",
    "title": "Memento"
  },
  "visitor": {
    "lab": "none",
    "figure": "umlClass",
    "priority": "lld",
    "category": "lld-behavioral",
    "track": "lld",
    "title": "Visitor"
  },
  "interpreter": {
    "lab": "none",
    "figure": "none",
    "priority": "lld",
    "category": "lld-behavioral",
    "track": "lld",
    "title": "Interpreter"
  },
  "specification-pattern": {
    "lab": "none",
    "figure": "none",
    "priority": "lld",
    "category": "lld-behavioral",
    "track": "lld",
    "title": "Specification Pattern"
  },
  "transactional-outbox": {
    "lab": "clickFlow",
    "figure": "outboxFlow",
    "priority": "gold",
    "category": "lld-dist-patterns",
    "track": "lld",
    "title": "Transactional Outbox"
  },
  "db-cache-dual-write": {
    "lab": "clickFlow",
    "figure": "none",
    "priority": "lld",
    "category": "lld-dist-patterns",
    "track": "lld",
    "title": "DB + Cache Dual Write"
  },
  "inbox-pattern": {
    "lab": "clickFlow",
    "figure": "none",
    "priority": "lld",
    "category": "lld-dist-patterns",
    "track": "lld",
    "title": "Inbox / Idempotent Consumer"
  },
  "cdc-relay": {
    "lab": "clickFlow",
    "figure": "none",
    "priority": "lld",
    "category": "lld-dist-patterns",
    "track": "lld",
    "title": "CDC Relay"
  },
  "sidecar": {
    "lab": "none",
    "figure": "outboxFlow",
    "priority": "lld",
    "category": "lld-dist-patterns",
    "track": "lld",
    "title": "Sidecar"
  },
  "ambassador": {
    "lab": "none",
    "figure": "outboxFlow",
    "priority": "lld",
    "category": "lld-dist-patterns",
    "track": "lld",
    "title": "Ambassador"
  },
  "saga-choreography": {
    "lab": "clickFlow",
    "figure": "none",
    "priority": "lld",
    "category": "lld-dist-patterns",
    "track": "lld",
    "title": "Saga Choreography"
  },
  "saga-orchestration": {
    "lab": "clickFlow",
    "figure": "none",
    "priority": "lld",
    "category": "lld-dist-patterns",
    "track": "lld",
    "title": "Saga Orchestration"
  },
  "cqrs-read-write-models": {
    "lab": "clickFlow",
    "figure": "none",
    "priority": "lld",
    "category": "lld-dist-patterns",
    "track": "lld",
    "title": "CQRS Read/Write Models"
  },
  "event-sourcing-projection": {
    "lab": "clickFlow",
    "figure": "none",
    "priority": "lld",
    "category": "lld-dist-patterns",
    "track": "lld",
    "title": "Event Sourcing Projection"
  },
  "claim-check": {
    "lab": "none",
    "figure": "outboxFlow",
    "priority": "lld",
    "category": "lld-dist-patterns",
    "track": "lld",
    "title": "Claim Check"
  },
  "process-manager": {
    "lab": "clickFlow",
    "figure": "none",
    "priority": "lld",
    "category": "lld-dist-patterns",
    "track": "lld",
    "title": "Process Manager"
  },
  "wire-tap": {
    "lab": "none",
    "figure": "outboxFlow",
    "priority": "lld",
    "category": "lld-dist-patterns",
    "track": "lld",
    "title": "Wire Tap"
  },
  "content-enricher": {
    "lab": "none",
    "figure": "outboxFlow",
    "priority": "lld",
    "category": "lld-dist-patterns",
    "track": "lld",
    "title": "Content Enricher"
  },
  "message-router": {
    "lab": "none",
    "figure": "outboxFlow",
    "priority": "lld",
    "category": "lld-dist-patterns",
    "track": "lld",
    "title": "Message Router"
  },
  "splitter-aggregator": {
    "lab": "none",
    "figure": "outboxFlow",
    "priority": "lld",
    "category": "lld-dist-patterns",
    "track": "lld",
    "title": "Splitter / Aggregator"
  },
  "competing-consumers": {
    "lab": "clickFlow",
    "figure": "none",
    "priority": "lld",
    "category": "lld-dist-patterns",
    "track": "lld",
    "title": "Competing Consumers"
  },
  "priority-queue-consumer": {
    "lab": "none",
    "figure": "outboxFlow",
    "priority": "lld",
    "category": "lld-dist-patterns",
    "track": "lld",
    "title": "Priority Queue Consumer"
  },
  "strangler-code-level": {
    "lab": "none",
    "figure": "outboxFlow",
    "priority": "lld",
    "category": "lld-dist-patterns",
    "track": "lld",
    "title": "Strangler at Code Level"
  },
  "fire-and-forget": {
    "lab": "none",
    "figure": "messagingLoop",
    "priority": "lld",
    "category": "lld-async",
    "track": "lld",
    "title": "Fire-and-Forget"
  },
  "request-reply": {
    "lab": "none",
    "figure": "messagingLoop",
    "priority": "lld",
    "category": "lld-async",
    "track": "lld",
    "title": "Request-Reply"
  },
  "pub-sub-pattern": {
    "lab": "queue",
    "figure": "none",
    "priority": "lld",
    "category": "lld-async",
    "track": "lld",
    "title": "Pub/Sub"
  },
  "point-to-point": {
    "lab": "none",
    "figure": "messagingLoop",
    "priority": "lld",
    "category": "lld-async",
    "track": "lld",
    "title": "Point-to-Point"
  },
  "work-queue": {
    "lab": "queue",
    "figure": "none",
    "priority": "lld",
    "category": "lld-async",
    "track": "lld",
    "title": "Work Queue"
  },
  "delayed-scheduled-messages": {
    "lab": "none",
    "figure": "messagingLoop",
    "priority": "lld",
    "category": "lld-async",
    "track": "lld",
    "title": "Delayed / Scheduled Messages"
  },
  "dead-letter-pattern": {
    "lab": "queue",
    "figure": "none",
    "priority": "lld",
    "category": "lld-async",
    "track": "lld",
    "title": "Dead Letter Pattern"
  },
  "backpressure-pattern": {
    "lab": "queue",
    "figure": "none",
    "priority": "lld",
    "category": "lld-async",
    "track": "lld",
    "title": "Backpressure Pattern"
  },
  "outbox-inbox-combo": {
    "lab": "queue",
    "figure": "none",
    "priority": "lld",
    "category": "lld-async",
    "track": "lld",
    "title": "Outbox + Inbox Combo"
  },
  "event-notification-vs-ecst": {
    "lab": "none",
    "figure": "messagingLoop",
    "priority": "lld",
    "category": "lld-async",
    "track": "lld",
    "title": "Event Notification vs ECST"
  },
  "rest-resource-modeling": {
    "lab": "none",
    "figure": "requestFlow",
    "priority": "lld",
    "category": "lld-api",
    "track": "lld",
    "title": "REST Resource Modeling"
  },
  "api-versioning-strategies": {
    "lab": "none",
    "figure": "requestFlow",
    "priority": "lld",
    "category": "lld-api",
    "track": "lld",
    "title": "API Versioning Strategies"
  },
  "pagination-offset-cursor": {
    "lab": "clickFlow",
    "figure": "none",
    "priority": "lld",
    "category": "lld-api",
    "track": "lld",
    "title": "Pagination (Offset vs Cursor)"
  },
  "error-contract-design": {
    "lab": "none",
    "figure": "requestFlow",
    "priority": "lld",
    "category": "lld-api",
    "track": "lld",
    "title": "Error Contract Design"
  },
  "correlation-trace-ids": {
    "lab": "clickFlow",
    "figure": "none",
    "priority": "lld",
    "category": "lld-api",
    "track": "lld",
    "title": "Correlation / Trace IDs"
  },
  "api-idempotency": {
    "lab": "clickFlow",
    "figure": "none",
    "priority": "lld",
    "category": "lld-api",
    "track": "lld",
    "title": "API Idempotency"
  },
  "contract-first-vs-code-first": {
    "lab": "none",
    "figure": "none",
    "priority": "lld",
    "category": "lld-api",
    "track": "lld",
    "title": "Contract-First vs Code-First"
  },
  "hateoas": {
    "lab": "none",
    "figure": "none",
    "priority": "lld",
    "category": "lld-api",
    "track": "lld",
    "title": "HATEOAS"
  },
  "grpc-service-design": {
    "lab": "none",
    "figure": "none",
    "priority": "lld",
    "category": "lld-api",
    "track": "lld",
    "title": "gRPC Service Design"
  },
  "graphql-schema-design": {
    "lab": "none",
    "figure": "none",
    "priority": "lld",
    "category": "lld-api",
    "track": "lld",
    "title": "GraphQL Schema Design"
  },
  "er-modeling": {
    "lab": "none",
    "figure": "er",
    "priority": "lld",
    "category": "lld-db",
    "track": "lld",
    "title": "ER Modeling"
  },
  "normal-forms-bcnf": {
    "lab": "none",
    "figure": "er",
    "priority": "lld",
    "category": "lld-db",
    "track": "lld",
    "title": "1NF–3NF / BCNF"
  },
  "denormalization-patterns": {
    "lab": "none",
    "figure": "er",
    "priority": "lld",
    "category": "lld-db",
    "track": "lld",
    "title": "Denormalization Patterns"
  },
  "primary-foreign-keys": {
    "lab": "none",
    "figure": "er",
    "priority": "lld",
    "category": "lld-db",
    "track": "lld",
    "title": "Primary / Foreign Keys"
  },
  "indexing-strategies": {
    "lab": "algorithm",
    "figure": "none",
    "priority": "lld",
    "category": "lld-db",
    "track": "lld",
    "title": "Indexing Strategies"
  },
  "soft-delete": {
    "lab": "none",
    "figure": "er",
    "priority": "lld",
    "category": "lld-db",
    "track": "lld",
    "title": "Soft Delete"
  },
  "audit-tables": {
    "lab": "none",
    "figure": "er",
    "priority": "lld",
    "category": "lld-db",
    "track": "lld",
    "title": "Audit Tables"
  },
  "optimistic-locking-schema": {
    "lab": "none",
    "figure": "er",
    "priority": "lld",
    "category": "lld-db",
    "track": "lld",
    "title": "Optimistic Locking Schema"
  },
  "multi-tenant-schema": {
    "lab": "none",
    "figure": "er",
    "priority": "lld",
    "category": "lld-db",
    "track": "lld",
    "title": "Multi-Tenant Schema"
  },
  "temporal-tables": {
    "lab": "none",
    "figure": "er",
    "priority": "lld",
    "category": "lld-db",
    "track": "lld",
    "title": "Temporal Tables"
  },
  "scd-type-1-2": {
    "lab": "none",
    "figure": "er",
    "priority": "lld",
    "category": "lld-db",
    "track": "lld",
    "title": "SCD Type 1 / 2"
  },
  "read-replica-routing": {
    "lab": "clickFlow",
    "figure": "none",
    "priority": "lld",
    "category": "lld-db",
    "track": "lld",
    "title": "Read Replica Routing"
  },
  "connection-pooling": {
    "lab": "metrics",
    "figure": "none",
    "priority": "lld",
    "category": "lld-db",
    "track": "lld",
    "title": "Connection Pooling"
  },
  "transactional-boundaries": {
    "lab": "none",
    "figure": "er",
    "priority": "lld",
    "category": "lld-db",
    "track": "lld",
    "title": "Transactional Boundaries"
  },
  "threads-vs-async": {
    "lab": "none",
    "figure": "architecture",
    "priority": "lld",
    "category": "lld-concurrency",
    "track": "lld",
    "title": "Threads vs Async"
  },
  "thread-pool": {
    "lab": "architecture",
    "figure": "none",
    "priority": "lld",
    "category": "lld-concurrency",
    "track": "lld",
    "title": "Thread Pool"
  },
  "producer-consumer": {
    "lab": "architecture",
    "figure": "none",
    "priority": "lld",
    "category": "lld-concurrency",
    "track": "lld",
    "title": "Producer-Consumer"
  },
  "readers-writers": {
    "lab": "architecture",
    "figure": "none",
    "priority": "lld",
    "category": "lld-concurrency",
    "track": "lld",
    "title": "Readers-Writers"
  },
  "lock-free-atomic": {
    "lab": "none",
    "figure": "architecture",
    "priority": "lld",
    "category": "lld-concurrency",
    "track": "lld",
    "title": "Lock-Free / Atomic"
  },
  "actor-model": {
    "lab": "none",
    "figure": "architecture",
    "priority": "lld",
    "category": "lld-concurrency",
    "track": "lld",
    "title": "Actor Model"
  },
  "reactive-streams": {
    "lab": "none",
    "figure": "architecture",
    "priority": "lld",
    "category": "lld-concurrency",
    "track": "lld",
    "title": "Reactive Streams"
  },
  "async-await-pitfalls": {
    "lab": "none",
    "figure": "architecture",
    "priority": "lld",
    "category": "lld-concurrency",
    "track": "lld",
    "title": "Async/Await Pitfalls"
  },
  "virtual-threads": {
    "lab": "none",
    "figure": "architecture",
    "priority": "lld",
    "category": "lld-concurrency",
    "track": "lld",
    "title": "Virtual Threads"
  },
  "structured-concurrency": {
    "lab": "none",
    "figure": "architecture",
    "priority": "lld",
    "category": "lld-concurrency",
    "track": "lld",
    "title": "Structured Concurrency"
  },
  "layered-architecture": {
    "lab": "none",
    "figure": "architecture",
    "priority": "lld",
    "category": "lld-ddd",
    "track": "lld",
    "title": "Layered Architecture"
  },
  "hexagonal-ports-adapters": {
    "lab": "none",
    "figure": "architecture",
    "priority": "lld",
    "category": "lld-ddd",
    "track": "lld",
    "title": "Hexagonal Ports & Adapters"
  },
  "bounded-context": {
    "lab": "none",
    "figure": "architecture",
    "priority": "lld",
    "category": "lld-ddd",
    "track": "lld",
    "title": "Bounded Context"
  },
  "aggregate-root": {
    "lab": "none",
    "figure": "architecture",
    "priority": "lld",
    "category": "lld-ddd",
    "track": "lld",
    "title": "Aggregate Root"
  },
  "domain-vs-integration-events": {
    "lab": "none",
    "figure": "architecture",
    "priority": "lld",
    "category": "lld-ddd",
    "track": "lld",
    "title": "Domain vs Integration Events"
  },
  "repository-pattern": {
    "lab": "none",
    "figure": "architecture",
    "priority": "lld",
    "category": "lld-ddd",
    "track": "lld",
    "title": "Repository Pattern"
  },
  "value-objects": {
    "lab": "none",
    "figure": "architecture",
    "priority": "lld",
    "category": "lld-ddd",
    "track": "lld",
    "title": "Value Objects"
  },
  "anti-corruption-code-boundary": {
    "lab": "none",
    "figure": "architecture",
    "priority": "lld",
    "category": "lld-ddd",
    "track": "lld",
    "title": "Anti-Corruption at Code"
  },
  "cqrs-handler-separation": {
    "lab": "none",
    "figure": "architecture",
    "priority": "lld",
    "category": "lld-ddd",
    "track": "lld",
    "title": "CQRS Handler Separation"
  },
  "event-storming-to-code": {
    "lab": "none",
    "figure": "none",
    "priority": "lld",
    "category": "lld-ddd",
    "track": "lld",
    "title": "Event Storming to Code"
  },
  "unit-integration-contract": {
    "lab": "none",
    "figure": "none",
    "priority": "lld",
    "category": "lld-testing",
    "track": "lld",
    "title": "Unit vs Integration vs Contract"
  },
  "test-doubles": {
    "lab": "none",
    "figure": "none",
    "priority": "lld",
    "category": "lld-testing",
    "track": "lld",
    "title": "Test Doubles"
  },
  "tdd-for-lld": {
    "lab": "none",
    "figure": "none",
    "priority": "lld",
    "category": "lld-testing",
    "track": "lld",
    "title": "TDD for LLD"
  },
  "property-based-testing": {
    "lab": "none",
    "figure": "none",
    "priority": "lld",
    "category": "lld-testing",
    "track": "lld",
    "title": "Property-Based Testing"
  },
  "consumer-driven-contracts": {
    "lab": "none",
    "figure": "none",
    "priority": "lld",
    "category": "lld-testing",
    "track": "lld",
    "title": "Consumer-Driven Contracts"
  },
  "mutation-testing": {
    "lab": "none",
    "figure": "none",
    "priority": "lld",
    "category": "lld-testing",
    "track": "lld",
    "title": "Mutation Testing"
  },
  "parking-lot": {
    "lab": "algorithm",
    "figure": "none",
    "priority": "lld",
    "category": "lld-classics",
    "track": "lld",
    "title": "Parking Lot"
  },
  "elevator": {
    "lab": "algorithm",
    "figure": "none",
    "priority": "lld",
    "category": "lld-classics",
    "track": "lld",
    "title": "Elevator"
  },
  "lru-cache": {
    "lab": "algorithm",
    "figure": "none",
    "priority": "gold",
    "category": "lld-classics",
    "track": "lld",
    "title": "LRU Cache"
  },
  "in-memory-pub-sub": {
    "lab": "algorithm",
    "figure": "none",
    "priority": "lld",
    "category": "lld-classics",
    "track": "lld",
    "title": "In-Memory Pub-Sub"
  },
  "rate-limiter-in-process": {
    "lab": "algorithm",
    "figure": "none",
    "priority": "lld",
    "category": "lld-classics",
    "track": "lld",
    "title": "Rate Limiter (In-Process)"
  },
  "acid": {
    "lab": "state",
    "figure": "none",
    "priority": "lld",
    "category": "lld-transactions",
    "track": "lld",
    "title": "ACID"
  },
  "isolation-levels": {
    "lab": "state",
    "figure": "none",
    "priority": "lld",
    "category": "lld-transactions",
    "track": "lld",
    "title": "Isolation Levels"
  },
  "two-pc": {
    "lab": "state",
    "figure": "none",
    "priority": "lld",
    "category": "lld-transactions",
    "track": "lld",
    "title": "2PC"
  },
  "three-pc": {
    "lab": "state",
    "figure": "none",
    "priority": "lld",
    "category": "lld-transactions",
    "track": "lld",
    "title": "3PC"
  },
  "saga": {
    "lab": "state",
    "figure": "none",
    "priority": "lld",
    "category": "lld-transactions",
    "track": "lld",
    "title": "Saga Pattern"
  },
  "tcc": {
    "lab": "state",
    "figure": "none",
    "priority": "lld",
    "category": "lld-transactions",
    "track": "lld",
    "title": "TCC"
  },
  "state-transition": {
    "lab": "state",
    "figure": "none",
    "priority": "lld",
    "category": "lld-transactions",
    "track": "lld",
    "title": "A→B→C State Transition"
  },
  "redis-lock": {
    "lab": "race",
    "figure": "none",
    "priority": "lld",
    "category": "lld-dist-locks",
    "track": "lld",
    "title": "Redis Lock"
  },
  "redlock": {
    "lab": "race",
    "figure": "none",
    "priority": "lld",
    "category": "lld-dist-locks",
    "track": "lld",
    "title": "Redlock Debate"
  },
  "zookeeper-lock": {
    "lab": "race",
    "figure": "none",
    "priority": "lld",
    "category": "lld-dist-locks",
    "track": "lld",
    "title": "ZooKeeper Locks"
  },
  "etcd-lease": {
    "lab": "race",
    "figure": "none",
    "priority": "lld",
    "category": "lld-dist-locks",
    "track": "lld",
    "title": "etcd Lease Locks"
  },
  "lease-expiration": {
    "lab": "race",
    "figure": "none",
    "priority": "lld",
    "category": "lld-dist-locks",
    "track": "lld",
    "title": "Lease Expiration"
  },
  "fencing-tokens": {
    "lab": "race",
    "figure": "none",
    "priority": "lld",
    "category": "lld-dist-locks",
    "track": "lld",
    "title": "Fencing Tokens"
  },
  "out-of-order": {
    "lab": "algorithm",
    "figure": "none",
    "priority": "lld",
    "category": "lld-event-ordering",
    "track": "lld",
    "title": "Out-of-order Events"
  },
  "duplicate-events": {
    "lab": "algorithm",
    "figure": "none",
    "priority": "lld",
    "category": "lld-event-ordering",
    "track": "lld",
    "title": "Duplicate Events"
  },
  "missing-events": {
    "lab": "algorithm",
    "figure": "none",
    "priority": "lld",
    "category": "lld-event-ordering",
    "track": "lld",
    "title": "Missing Events"
  },
  "event-reordering": {
    "lab": "algorithm",
    "figure": "none",
    "priority": "lld",
    "category": "lld-event-ordering",
    "track": "lld",
    "title": "Event Reordering"
  },
  "clock-skew": {
    "lab": "algorithm",
    "figure": "none",
    "priority": "lld",
    "category": "lld-event-ordering",
    "track": "lld",
    "title": "Clock Skew"
  },
  "lamport-clock": {
    "lab": "algorithm",
    "figure": "none",
    "priority": "lld",
    "category": "lld-event-ordering",
    "track": "lld",
    "title": "Lamport Clock"
  },
  "vector-clock": {
    "lab": "algorithm",
    "figure": "none",
    "priority": "lld",
    "category": "lld-event-ordering",
    "track": "lld",
    "title": "Vector Clock"
  },
  "idempotency-key": {
    "lab": "race",
    "figure": "none",
    "priority": "lld",
    "category": "lld-idempotency",
    "track": "lld",
    "title": "Idempotency-Key"
  },
  "exactly-once": {
    "lab": "race",
    "figure": "none",
    "priority": "lld",
    "category": "lld-idempotency",
    "track": "lld",
    "title": "Exactly Once"
  },
  "deduplication": {
    "lab": "race",
    "figure": "none",
    "priority": "lld",
    "category": "lld-idempotency",
    "track": "lld",
    "title": "Deduplication"
  },
  "optimistic": {
    "lab": "state",
    "figure": "none",
    "priority": "lld",
    "category": "lld-concurrency-strategies",
    "track": "lld",
    "title": "Optimistic Concurrency"
  },
  "pessimistic": {
    "lab": "state",
    "figure": "none",
    "priority": "lld",
    "category": "lld-concurrency-strategies",
    "track": "lld",
    "title": "Pessimistic Concurrency"
  },
  "hybrid": {
    "lab": "state",
    "figure": "none",
    "priority": "lld",
    "category": "lld-concurrency-strategies",
    "track": "lld",
    "title": "Hybrid Locking"
  }
};
