/**
 * Generate scripts/sim-map.json from registry metadata.
 * Run: node scripts/gen-sim-map.mjs
 */
import { writeFileSync } from "fs";
import { join, dirname } from "path";
import { fileURLToPath } from "url";
import { generateSimMap } from "./lib/sim-map-gen.mjs";

const ROOT = join(dirname(fileURLToPath(import.meta.url)), "..");
const map = generateSimMap();
writeFileSync(join(ROOT, "scripts", "sim-map.json"), JSON.stringify(map, null, 2), "utf8");

const jsContent = `// Auto-generated by scripts/gen-sim-map.mjs — do not edit manually
export const SIM_MAP = ${JSON.stringify(map.topics, null, 2)};
`;
writeFileSync(join(ROOT, "js", "sim", "lab", "simMap.js"), jsContent, "utf8");
console.log(`Wrote ${Object.keys(map.topics).length} entries to sim-map.json and simMap.js`);
